### PR TITLE
* updating for 1.08 Steam patch

### PR DESCRIPTION
**Pull request by Pobega**
This is the updated offset for Steam patch 1.08.

Verified working on my machine.

### CODE REVIEW

**Comment by thraemonium** [comment]
You don't have a release? Somehow I can't build the project using pyinstaller

**Comment by TrickNachos** [comment]
How do I use this to update TekkenBotPrime myself?  I'm searching where MemoryAddressEnum.py is but I can't find it?  Should I change memory_address.config?

**Comment by thraemonium** [comment]
You need to use pyinstaller, but it's not building properly on my end

**Comment by Pobega** [comment]
Pull requests aren't for support, please take the conversation over to the Issues section. Thanks.

**Comment by Juggale** [comment]
Would you be able to upload all the files for a simple download of the working build?

**Comment by TrickNachos** [comment]
Yes please Pobega.  The fate of the world is in your hands!  Can you just upload an already compiled version for us plebs?

**Comment by honkyturtle** [comment]
For future reference can you explain how you got the offset value.

**Comment by Pobega** [comment]
Sorry for the late reply; Roguelike2D uploaded a video tutorial on how to do it himself, it took me a while to find:

https://www.youtube.com/watch?v=wqY3A6R-gVM&feature=youtu.be

**Comment by Pobega** [comment]
I'm closing this PR since it's a bit outdated, but I'll see about making a build for the current Tekken patch sometime this weekend if someone else hasn't done it already.

**Pull request closed without merging**
